---
- name: Fail when os family is not Debian.
  fail:
    msg: "This is not a debian based system ({{ ansible_os_family }})."
  when: ansible_os_family != 'Debian'

- name: Include distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "lsb_id_{{ ansible_lsb.id }}.yml"
    - "distribution_{{ ansible_distribution }}_{{ ansible_lsb.major_release }}.yml"
    - "distribution_{{ ansible_distribution }}.yml"
    - "default.yml"

- name: Configure proxy.
  template:
    src: apt.conf.d/00proxy.j2
    dest: /etc/apt/apt.conf.d/00proxy
    mode: 0644
  when: apt_config_http_proxy is defined or apt_config_https_proxy is defined
  register: _apt_proxy_result
  tags:
    - apt-cacher-ng

- name: Delete proxy config.
  file:
    path: /etc/apt/apt.conf.d/00proxy
    state: absent
  when:
    - apt_config_http_proxy is not defined
    - apt_config_https_proxy is not defined

- name: Delete old apt-cacher-ng.
  file:
    path: /etc/apt/apt.conf.d/00apt-cacher-ng
    state: absent

- name: Configure apt lists and priorities
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - src: etc/apt/sources.list.j2
      dest: /etc/apt/sources.list
    - src: etc/apt/sources.list.d/stable.list.j2
      dest: /etc/apt/sources.list.d/stable.list
    - src: etc/apt/preferences.d/stable.pref.j2
      dest: /etc/apt/preferences.d/stable.pref
  register: _apt_config_result

- name: Update apt  # noqa 503
  apt:
    update_cache: yes
  when: _apt_config_result.changed or _apt_proxy_result.changed
