apt_config_debs:
  - uri: http://ftp.debian.org/debian
    suite: "{{ apt_config_distribution_release }}"
  - uri: http://ftp.debian.org/debian
    suite: "{{ apt_config_distribution_release }}-updates"
  - uri: http://security.debian.org
    suite: "{{ apt_config_distribution_release }}/updates"
  - uri: http://ftp.debian.org/debian
    suite: "{{ apt_config_distribution_release }}-backports"

apt_config_components_default:
  - main
  - contrib
